apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-appset
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/TheMontents/app-of-apps.git
      revision: HEAD
      # scan under apps/ for sub-folders
      directories:
      - path: apps/*

  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default

      source:
        repoURL: https://github.com/TheMontents/app-of-apps.git
        targetRevision: HEAD
        path: '{{path}}'

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}-demo'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
