apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ghost-demo
  namespace: argocd
spec:
  project: default

  # Zeigt auf das Verzeichnis mit deinen plain-YAMLs
  source:
    repoURL: https://github.com/TheMontents/app-of-apps.git
    path: apps/ghost-app
    targetRevision: HEAD

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
